TASK_CREATION_HOUR = 18
TASK_CREATION_MINUTE = 15
TASKS_PER_AREA = 1

ASSIGNMENT_HOURS = [9, 10, 11]
TASKS_PER_PERSON_PER_ASSIGNMENT = 1
MAX_TASKS_PER_DAY = 3

PROXIMITY_BONUS = 5

MAX_AREAS_TO_CREATE_TASKS_FOR = 5
TASK_EXPIRY_HOURS = 24

USER_ROLE = 'user'
AREA_QUESTION_TEXT = 'Which general area on campus are you reporting from?'

ENABLE_DEBUG_LOGS = True
